name: Prepare branch name
description: An action to prepare the branch name to be used by actions like actions/upload-artifact. This action parses the current branch name to replace the slashes with underscores

outputs:
  BRANCH_NAME:
    description: "The prepared branch name"
    value: ${{ steps.prepare_branch_name.outputs.name }}

runs:
  using: composite
  steps:
    - name: "Prepare branch name"
      id: prepare_branch_name
      run: |
        BRANCH_NAME=$(echo "${{ github.head_ref || github.ref_name }}" | sed "s/\//\_/g")
        echo "Prepared branch name: $BRANCH_NAME"
        echo "name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
      shell: bash
